- job:
    name: chart-vendor
    parent: golang-go
    abstract: true
    pre-run: playbooks/chart-vendor/pre.yaml
    run: playbooks/chart-vendor/run.yaml
    required-projects:
      - vexxhost/chart-vendor
    vars:
      go_version: 1.23.1

- project:
    check:
      jobs:
        - noop
    gate:
      jobs:
        - noop
