name: chart-vendor
description: Ensure all charts are vendored with all the patches.

inputs:
  working-directory:
    description: Path to the working directory
    default: ${{ github.workspace }}
  config-file:
    description: Configuration file for the vendored charts
    default: .charts.yml
  charts-root:
    description: Root path where charts are generated
    default: charts

runs:
  using: composite
  steps:
    - shell: bash
      run: sudo apt-get install patchutils
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: go.mod
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: go install
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: chart-vendor --config-file ${{ inputs.config-file }} --charts-root ${{ inputs.charts-root }} --check
