name: chart-vendor
description: Ensure all charts are vendored with all the patches.

inputs:
  working-directory:
    description: Path to the working directory
    default: ${{ github.workspace }}
  config-file:
    description: Configuration file for the vendored charts
    default: .charts.yaml
  charts-root:
    description: Root path where charts are generated
    default: charts

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: go run main.go --config-file ${{ inputs.working-directory }}/${{ inputs.config-file }} --charts-root ${{ inputs.working-directory }}/${{ inputs.charts-root }} --check
